name: FileAutomation Dev Python3.10

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
      - name: Dir Module Test
        run: python ./tests/unit_test/local/dir/dir_test.py
      - name: File Module Test
        run: python ./tests/unit_test/local/file/test_file.py
      - name: Zip Module Test
        run: python ./tests/unit_test/local/zip/zip_test.py